# Generated by Django 5.0.1 on 2025-04-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lyrics', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('sound', models.FileField(blank=True, null=True, upload_to='media')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
